BCR.PracticaMinions4.UIL/Controllers/ReportsController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Data;
using System.Web.Mvc;
using clsConstantes = BCR.PracticaMinions4.LIL.Constantes;

namespace BCR.PracticaMinions4.UIL.Controllers
{
    /// <summary>
    ///     <createddate>2020-02-10</createddate>
    ///     <company>Grupo Babel</company>
    ///     <lastmodificationdate>2020-02-10</lastmodificationdate>
    ///     <lastmodificationdescription>
    ///         Se agregaron los comentarios a la clase.
    ///     </lastmodificationdescription>
    ///     <lastmodifierautor>Jeison Jiménez</lastmodifierautor>
    /// </summary>
    public class ReportsController : Controller
    {
        BLL.Reservas bllReservas = new BLL.Reservas();  

        /// <summary>
        ///     Metodo que lleva a una pagina con un reporte de reservas
        /// </summary>
        /// <returns>Vista de reporte de reservas</returns>
        public ActionResult Reservas(int idVuelo)
        {
            ReportViewer viewer = new ReportViewer();
            try
            {
                //Datasource
                var resultadoConsulta = bllReservas.MostrarReservas();
              
                //Seteo del reporte
                viewer.ShowExportControls = true;
                viewer.ShowPrintButton = true;
                viewer.ProcessingMode = ProcessingMode.Local;
                viewer.SizeToReportContent = true;
                viewer.AsyncRendering = true;
                viewer.LocalReport.ReportPath = clsConstantes.Reportes.RESERVAS;

                DataTable dt = new DataTable();
                dt.Columns.Add(clsConstantes.Columnas.CODIGORESERVA);
                dt.Columns.Add(clsConstantes.Columnas.CODIGOVUELO);
                dt.Columns.Add(clsConstantes.Columnas.DESTINOS);
                dt.Columns.Add(clsConstantes.Columnas.FECHASALIDA);
                dt.Columns.Add(clsConstantes.Columnas.NOMBRECLIENTE);
                dt.Columns.Add(clsConstantes.Columnas.CANTIDADNOFUMADORES);
                dt.Columns.Add(clsConstantes.Columnas.CANTIDADFUMADORES);

                foreach (var objReserva in resultadoConsulta.objetoRespuesta)
                {
                    DataRow row = dt.NewRow();
                    row[clsConstantes.Columnas.CODIGORESERVA] = objReserva.codigoReserva;
                    row[clsConstantes.Columnas.CODIGOVUELO] = objReserva.codigoVuelo;
                    row[clsConstantes.Columnas.DESTINOS] = objReserva.destinos;
                    row[clsConstantes.Columnas.FECHASALIDA] = objReserva.fechaSalida;
                    row[clsConstantes.Columnas.NOMBRECLIENTE] = objReserva.nombreCliente;
                    row[clsConstantes.Columnas.CANTIDADNOFUMADORES] = objReserva.cantidadNoFumadores;
                    row[clsConstantes.Columnas.CANTIDADFUMADORES] = objReserva.cantidadFumadores;
                    dt.Rows.Add(row);
                }

                DataSet ds = new DataSet(clsConstantes.Datasets.RESERVAS);
                ds.Tables.Add(dt);
                ReportParameter p1 = new ReportParameter("idVuelo", idVuelo.ToString());
                viewer.LocalReport.SetParameters(new ReportParameter[] { p1 });
                viewer.LocalReport.DataSources.Add(new ReportDataSource(clsConstantes.Datasets.MYDATASET, ds.Tables[0]));
                ViewBag.ReportViewer = viewer;
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Reservas");
                return Content(CodigoJavaScript);
            }
            return View();
        }
    }
}

BCR.PracticaMinions4.UIL/Controllers/VuelosController.cs
using BCR.PracticaMinions4.ETL;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using CapaBLL = BCR.PracticaMinions4.BLL;
using CapaETL = BCR.PracticaMinions4.ETL;
using clsConstantes = BCR.PracticaMinions4.LIL.Constantes;
using Mensajes = BCR.PracticaMinions4.LIL.Recursos.Mensajes;

namespace BCR.PracticaMinions4.UIL.Controllers
{
    /// <summary>
    ///     <createddate>2020-02-05</createddate>
    ///     <company>Grupo Babel</company>
    ///     <lastmodificationdate>2020-02-05</lastmodificationdate>
    ///     <lastmodificationdescription>
    ///         Se agregaron los comentarios a la clase.
    ///     </lastmodificationdescription>
    ///     <lastmodifierautor>Jeison Jiménez</lastmodifierautor>
    /// </summary>
    public class VuelosController : Controller
    {
        #region Inicializacion de variables
        CapaETL.Respuesta respuesta = new CapaETL.Respuesta();
        CapaBLL.Destinos bllDestinos = new CapaBLL.Destinos();
        CapaBLL.Vuelos bllVuelos = new CapaBLL.Vuelos();
        CapaBLL.Reservas bllReservas = new CapaBLL.Reservas();
        #endregion

        #region Inicio
        /// <summary>
        ///     Método que retorna una vista
        /// </summary>
        /// <returns>Vista inicial</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///     Método que retorna una vista
        /// </summary>
        /// <returns>Vista de inicio de los vuelos</returns>
        public ActionResult InicioVuelos()
        {
            return View();
        }
        #endregion

        #region Destinos
        /// <summary>
        ///     Método que retorna una vista, con un modelo de destinos
        /// </summary>
        /// <returns>Vista de destinos</returns>
        public ActionResult Destinos()
        {
            try
            {
                return View(bllDestinos.MostrarDestinos().objetoRespuesta);
            }
            catch(Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Destinos");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Método que retorna una vista donde se agregan destinos
        /// </summary>
        /// <returns>Vista donde se agregan destinos</returns>
        public ActionResult AgregarDestinos()
        {
            return View();
        }

        /// <summary>
        ///     Método que inserta un destino y retorna un codigo de JS que muestra un mensaje de respuesta
        /// </summary>
        /// <param name="txtDestinoSalida"></param>
        /// <param name="txtDestinoLlegada"></param>
        /// <returns>Codigo javascript</returns>
        public ActionResult InsertarDestino(string txtDestinoSalida, string txtDestinoLlegada)
        {
            try
            {
                string CodigoJavaScript;
                if (string.IsNullOrEmpty(txtDestinoSalida) || string.IsNullOrEmpty(txtDestinoLlegada))
                {
                    //Se le da formato a la funcion javascript de retorno
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjErrorCamposVacios, "/Vuelos/AgregarDestinos");
                }
                else
                {
                    CapaETL.Destino destino = new CapaETL.Destino();
                    destino.destinoSalida = txtDestinoSalida;
                    destino.destinoLlegada = txtDestinoLlegada;

                    respuesta = bllDestinos.InsertarDestinos(destino);
                    if (respuesta.codigoRespuesta == clsConstantes.CodigosRespuestas.CODIGOCORRECTO)
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjDestinoAgregado, "/Vuelos/Destinos");
                    }
                    else
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, respuesta.mensajeRespuesta, "/Vuelos/Destinos");
                    }
                }
                return Content(CodigoJavaScript);
            }
            catch(Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Destinos");
                return Content(CodigoJavaScript);
            }           
        }

        /// <summary>
        ///     Método que devuelve una vista con un modelo de destinos, donde se modifica un usuario
        /// </summary>
        /// <param name="idDestino"></param>
        /// <returns></returns>
        public ActionResult ModificarDestino(int idDestino)
        {
            try
            {
                CapaETL.Destino destino = new CapaETL.Destino();
                destino.codigoDestino = idDestino;
                return View(bllDestinos.SeleccionarDestino(destino).objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Destinos");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Método que modifica un destino y retorna un codigo de JS que muestra un mensaje de respuesta
        /// </summary>
        /// <param name="txtCodigo"></param>
        /// <param name="txtDestinoSalida"></param>
        /// <param name="txtDestinoLlegada"></param>
        /// <returns>Vista de actualizar destinos</returns>
        public ActionResult ActualizarDestino(string txtCodigo, string txtDestinoSalida, string txtDestinoLlegada)
        {
            try
            {
                string CodigoJavaScript;
                if (string.IsNullOrEmpty(txtDestinoSalida) || string.IsNullOrEmpty(txtDestinoLlegada))
                {
                    //Se le da formato a la funcion javascript de retorno
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjErrorCamposVacios, "/Vuelos/AgregarDestinos");
                }
                else
                {
                    CapaETL.Destino destino = new CapaETL.Destino();
                    destino.codigoDestino = Convert.ToInt32(txtCodigo);
                    destino.destinoSalida = txtDestinoSalida;
                    destino.destinoLlegada = txtDestinoLlegada;

                    respuesta = bllDestinos.ModificarDestino(destino);
                    if (respuesta.codigoRespuesta == clsConstantes.CodigosRespuestas.CODIGOCORRECTO)
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjDestinoModificado, "/Vuelos/Destinos");
                    }
                    else
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, respuesta.mensajeRespuesta, "/Vuelos/Destinos");
                    }
                }
                return Content(CodigoJavaScript);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Destinos");
                return Content(CodigoJavaScript);
            }
        }
        #endregion

        #region Vuelos
        /// <summary>
        ///     Método de vista de inicio de los vuelos
        /// </summary>
        /// <returns>Vista con los vuelos</returns>
        public ActionResult Vuelos()
        {
            try
            {
                return View(bllVuelos.MostrarVuelos().objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Vuelos");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Retorna una vista donde se agregan los vuelos
        /// </summary>
        /// <returns>Vista agregar vuelos</returns>
        public ActionResult AgregarVuelos()
        {
            try
            {
                return View(bllDestinos.MostrarDestinos().objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Vuelos/Vuelos");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Método que inserta los vuelos 
        /// </summary>
        /// <param name="txtCapacidad"></param>
        /// <param name="txtFecha"></param>
        /// <param name="optDestinos"></param>
        /// <returns>Codigo JS con mensaje de respuesta</returns>
        public ActionResult InsertarVuelos(string txtCapacidad, string txtFecha, string optDestinos)
        {
            try
            {
                string CodigoJavaScript;
                if (string.IsNullOrEmpty(txtCapacidad) || string.IsNullOrEmpty(txtFecha) || string.IsNullOrEmpty(optDestinos))
                {
                    //Se le da formato a la funcion javascript de retorno
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjErrorCamposVacios, "/Vuelos/AgregarVuelos");
                }
                else
                {
                    CapaETL.Vuelo vuelo = new CapaETL.Vuelo();
                    vuelo.capacidad = Convert.ToInt32(txtCapacidad);
                    vuelo.fechaSalida = Convert.ToDateTime(txtFecha);

BCR.PracticaMinions4.UIL/Views/Vuelos/AgregarDestinos.cshtml
@model BCR.PracticaMinions4.ETL.Destino

@{
    ViewBag.Title = "AgregarDestinos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Destinos</h2>

<table style="width: 35%">
    @using (Html.BeginForm("InsertarDestino", "Vuelos", FormMethod.Post))
    {
        <tr>
            <td align="left">
                Destino Salida:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtDestinoSalida" class="form-control"/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Destino Llegada:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtDestinoLlegada" class="form-control" />
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Insertar Destino</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/AgregarReservas.cshtml
@model List<BCR.PracticaMinions4.ETL.Vuelo>
@{
    ViewBag.Title = "AgregarReservas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Reservas</h2>
<table style="width: 100%">
    <tr>
        <td style="width: 25%" align="left">
            <h6 id="lblFumadores">Asientos disponibles para fumadores:</h6>
        </td>
        <td style="width: 30%" align="left">
            <label id="lblDisponiblesFumadores">(Seleccione un vuelo)</label>
        </td>
        <td style="width: 27%" align="left">
            <h6 id="lblNoFumadores">Asientos disponibles para no fumadores:</h6>
        </td>
        <td style="width: 80%" align="left">
            <label id="lblDisponiblesNoFumadores">(Seleccione un vuelo)</label>
        </td>
    </tr>
    <tr>
    </tr>
</table>
<br />
<table style="width: 50%">
    @using (Html.BeginForm("InsertarReservas", "Vuelos", FormMethod.Post))
    {
        <tr>
            <td align="left" style="width: 50%">
                <h6>Nombre del cliente:</h6>
            </td>
            <td style="width: 40%">
                <input type="text" name="txtNombre" class="form-control" />
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 50%">
                <h6>Cantidad de asientos de fumadores:</h6>
            </td>
            <td style="width: 40%">
                <input type="text" name="txtFumadores" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 50%">
                <h6>Cantidad de asientos de no fumadores:</h6>
            </td>
            <td style="width: 40%">
                <input type="text" name="txtNofumadores" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 50%">
                <h6>Vuelo:</h6>
            </td>
            <td style="width: 40%">
                <select id="optVuelos" name="optVuelos" class="form-control" onchange="cargarDisponibles()">
                    <option value="0">Seleccione un vuelo</option>
                    @{
                        foreach (var vuelo in Model)
                        {
                            <option value="@vuelo.codigoVuelo">@vuelo.destinos - @vuelo.fechaSalida</option>
                        }
                    }
                </select>

            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Insertar Reserva</button>
            </td>
        </tr>
    }
</table>

<script>
    function cargarDisponibles() {
        var url = "@Url.Action("Disponibles","Vuelos")";
        var idVuelo = document.getElementById("optVuelos").value;
        var data = { idVuelo: idVuelo };
        if (idVuelo != 0) {
            $.post(url, data).done(function (data) {
                document.getElementById("lblDisponiblesFumadores").innerHTML = data["disponiblesFumadores"];
                document.getElementById("lblDisponiblesNoFumadores").innerHTML = data["disponiblesNoFumadores"];
            }).fail(function () {
                alert("error")
            });
        } else {
             document.getElementById("lblDisponiblesFumadores").innerHTML ="(Seleccione un vuelo)";
             document.getElementById("lblDisponiblesNoFumadores").innerHTML = "(Seleccione un vuelo)";
        }
    };
</script> 

BCR.PracticaMinions4.UIL/Views/Vuelos/AgregarVuelos.cshtml
@model List<BCR.PracticaMinions4.ETL.Destino>
@{
    ViewBag.Title = "AgregarVuelos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Vuelos</h2>

<table style="width: 35%">
    @using (Html.BeginForm("InsertarVuelos", "Vuelos", FormMethod.Post))
    {
        <tr>
            <td align="left">
                Capacidad:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtCapacidad" class="form-control" />
            </td>
        </tr>
        <tr>
            <td align="left">
                Fecha:
            </td>
            <td style="width: 50%">
                <input type="datetime-local" name="txtFecha" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left">
                Destinos:
            </td>
            <td style="width: 50%">
                <select name="optDestinos" class="form-control">
                    @{
                        foreach (var destino in Model)
                        {
                            <option value="@destino.codigoDestino">@destino.destinos</option>
                        }
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Insertar Vuelo</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/Destinos.cshtml
@model List<BCR.PracticaMinions4.ETL.Destino>
@{
    ViewBag.Title = "Destinos";
}

<h2>Destinos</h2>
<table style="width: 100%">
    <tr>
        <td style="width: 80%" align="right">
        </td>
        <td style="width: 12%">
            <button type="button" class="btn btn-success" onclick="location.href='/Vuelos/AgregarDestinos'">Agregar Destino</button>
        </td>
    </tr>
</table>
<table class="table table-bordered">
    <thead class="bg-info">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Destino de salida</th>
            <th scope="col">Destino de llegada</th>
            <th scope="col">Modificar</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var destino in Model)
            {
                <tr>
                    <th scope="col">@destino.codigoDestino</th>
                    <th scope="col">@destino.destinoSalida</th>
                    <th scope="col">@destino.destinoLlegada</th>
                    <th>
                        <button type="button" class="btn btn-primary"
                                onclick="location.href='@Url.Action("ModificarDestino", "Vuelos",
                            new { idDestino = destino.codigoDestino })';return false;">
                            Modificar
                        </button>
                    </th>
                </tr>
            }
        }
    </tbody>
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/Index.cshtml
@{
    ViewBag.Title = "Práctica minions 4";
}

<h2>@ViewBag.Title</h2>
<br />
<table>
    <tr>
        <td>
            <button type="button" class="btn btn-info btn-lg"  onclick="location.href='/Vuelos/InicioVuelos'">Módulo Vuelos</button>
        </td>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Evaluaciones/Index'">Módulo Evaluaciones</button>
        </td>
    </tr>
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/InicioVuelos.cshtml
@{
    ViewBag.Title = "Inicio Vuelos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>
<br />
<table>
    <tr>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Vuelos/Destinos'">Destinos</button>
        </td>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Vuelos/Vuelos'">Vuelos</button>
        </td>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Vuelos/Reservas'">Reservas</button>
        </td>
    </tr>
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/ModificarDestino.cshtml
@model List<BCR.PracticaMinions4.ETL.Destino>

@{
    ViewBag.Title = "ModificarDestino";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modificar Destino</h2>

<table>
    @using (Html.BeginForm("ActualizarDestino", "Vuelos", FormMethod.Post))
    {
        <tr>
            <td align="left">
                Código:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtCodigo" class="form-control" value="@Model[0].codigoDestino" readonly/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Destino Salida:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtDestinoSalida" class="form-control" value="@Model[0].destinoSalida"/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Destino Llegada:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtDestinoLlegada" class="form-control" value="@Model[0].destinoLlegada"/>
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Modificar Destino</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/ModificarVuelo.cshtml
@model BCR.PracticaMinions4.UIL.Controllers.ViewModel

@{
    ViewBag.Title = "ModificarVuelo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Modificar Vuelo</h2>

<table style="width: 35%">
    @using (Html.BeginForm("ActualizarVuelo", "Vuelos", FormMethod.Post))
    {
        <tr>
            <td align="left">
                Código:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtCodigoVuelo" class="form-control" value="@Model.listaVuelos[0].codigoVuelo" readonly/>
            </td>
        </tr>
        <tr>
            <td align="left">
                Capacidad:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtCapacidad" class="form-control" value="@Model.listaVuelos[0].capacidad" />
            </td>
        </tr>
        <tr>
            <td align="left">
                Fecha:
            </td>
            <td style="width: 50%">
                <input type="datetime-local" name="txtFecha" class="form-control" value="@Model.listaVuelos[0].fechaSalida.ToString("yyyy-MM-dd HH:mm:ss").Replace(' ','T')">
            </td>
        </tr>
        <tr>
            <td align="left">
                Destinos:
            </td>
            <td style="width: 50%">
                <select name="optDestinos" class="form-control">
                    @{
                        foreach (var destino in Model.listaDestinos)
                        {
                            if (destino.codigoDestino == @Model.listaVuelos[0].codigoDestino)
                            {
                                <option value="@destino.codigoDestino" selected>@destino.destinos</option>
                            }
                            else
                            {
                                <option value="@destino.codigoDestino">@destino.destinos</option>
                            }

                        }
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Modificar Vuelo</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/Reservas.cshtml
@model List<BCR.PracticaMinions4.ETL.Reserva>

@{
    ViewBag.Title = "Reservas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Reservas</h2>

<table style="width: 100%">
    <tr>
        <td style="width: 80%" align="right">
        </td>
        <td style="width: 12%">
            <button type="button" class="btn btn-success" onclick="location.href='/Vuelos/AgregarReservas'">Agregar Reserva</button>
        </td>
    </tr>
</table>
<table class="table table-bordered">
    <thead class="bg-info">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Vuelo</th>
            <th scope="col">Salida del vuelo</th>
            <th scope="col">Nombre del Cliente</th>
            <th scope="col">Cantidad fumadores</th>
            <th scope="col">Cantidad no fumadores</th>
            <th scope="col">Cancelar</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var reserva in Model)
            {
                <tr>
                    <th scope="col">@reserva.codigoReserva</th>
                    <th scope="col">@reserva.destinos</th>
                    <th scope="col">@reserva.fechaSalida</th>
                    <th scope="col">@reserva.nombreCliente</th>
                    <th scope="col">@reserva.cantidadFumadores</th>
                    <th scope="col">@reserva.cantidadNoFumadores</th>
                    <th>
                        <button type="button" class="btn btn-danger"
                                onclick="location.href='@Url.Action("CancelarReservas", "Vuelos",
                            new { idReserva = reserva.codigoReserva })';return false;">
                            Cancelar
                        </button>
                    </th>
                </tr>
            }
        }
    </tbody>
</table>

BCR.PracticaMinions4.UIL/Views/Vuelos/Vuelos.cshtml
@model List<BCR.PracticaMinions4.ETL.Vuelo>

@{
    ViewBag.Title = "Vuelos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Vuelos</h2>
<table style="width: 100%">
    <tr>
        <td style="width: 80%">
        </td>
        <td style="width: 12%">
            <button type="button" class="btn btn-success" onclick="location.href='/Vuelos/AgregarVuelos'">Agregar Vuelo</button>
        </td>
    </tr>
</table>
<table class="table table-bordered">
    <thead class="bg-info">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Destino</th>
            <th scope="col">Capacidad</th>
            <th scope="col">Fecha de salida</th>
            <th scope="col">Modificar</th>
            <th scope="col">Reservas</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var vuelo in Model)
            {
                <tr>
                    <th scope="col">@vuelo.codigoVuelo</th>
                    <th scope="col">@vuelo.destinos</th>
                    <th scope="col">@vuelo.capacidad</th>
                    <th scope="col">@vuelo.fechaSalida</th>
                    <th>
                        <button type="button" class="btn btn-primary"
                                onclick="location.href='@Url.Action("ModificarVuelo", "Vuelos",
                            new { idVuelo = vuelo.codigoVuelo })';return false;">
                            Modificar
                        </button>
                    </th>
                    <th>
                        <button type="button" class="btn btn-primary"
                                onclick="location.href='@Url.Action("Reservas", "Reports",
                            new { idVuelo = vuelo.codigoVuelo })';return false;">
                            Ver Reporte reservas
                        </button>
                    </th>
                </tr>
            }
        }
    </tbody>
</table>