BCR.PracticaMinions4.UIL/Controllers/EvaluacionesController.cs
using System;
using System.Web.Mvc;
using CapaBLL = BCR.PracticaMinions4.BLL;
using CapaETL = BCR.PracticaMinions4.ETL;
using clsConstantes = BCR.PracticaMinions4.LIL.Constantes;
using Mensajes = BCR.PracticaMinions4.LIL.Recursos.Mensajes;

namespace BCR.PracticaMinions4.UIL.Controllers
{
    /// <summary>
    ///     <createddate>2020-02-05</createddate>
    ///     <company>Grupo Babel</company>
    ///     <lastmodificationdate>2020-02-05</lastmodificationdate>
    ///     <lastmodificationdescription>
    ///         Se agregaron los comentarios a la clase.
    ///     </lastmodificationdescription>
    ///     <lastmodifierautor>Jeison Jiménez</lastmodifierautor>
    /// </summary>
    public class EvaluacionesController : Controller
    {
        #region Inicializacion de variables
        CapaETL.Respuesta respuesta = new CapaETL.Respuesta();
        CapaBLL.Evaluaciones bllEvaluaciones = new CapaBLL.Evaluaciones();
        CapaBLL.Calificaciones bllCalificaciones = new CapaBLL.Calificaciones();
        #endregion

        #region Evaluaciones
        /// <summary>
        ///     Metodo que retorna la vista inicial
        /// </summary>
        /// <returns>Vista index</returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        ///     Metodo que retorna la vista de evaluaciones con un modelo de evaluaciones
        /// </summary>
        /// <returns>Vista evaluaciones</returns>
        public ActionResult Evaluaciones()
        {
            try
            {
                return View(bllEvaluaciones.MostrarEvaluaciones().objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Evaluaciones/Evaluaciones");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Metodo que retorna la vista donde se agregan evaluaciones
        /// </summary>
        /// <returns>Vista agregar evaluaciones</returns>
        public ActionResult AgregarEvaluaciones()
        {
            return View();
        }

        /// <summary>
        ///     Metodo que inserta las evaluaciones
        /// </summary>
        /// <param name="txtNombre"></param>
        /// <param name="txtDescripcion"></param>
        /// <param name="txtCantidad"></param>
        /// <returns>Codigo js que tiene un mensaje de respuesta</returns>
        public ActionResult InsertarEvaluaciones(string txtNombre, string txtDescripcion, string txtCantidad)
        {
            try
            {
                string CodigoJavaScript;
                if (string.IsNullOrEmpty(txtNombre) || string.IsNullOrEmpty(txtDescripcion) || string.IsNullOrEmpty(txtCantidad))
                {
                    //Se le da formato a la funcion javascript de retorno
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjErrorCamposVacios, "/Evaluaciones/AgregarEvaluaciones");
                }
                else
                {
                    CapaETL.Evaluacion evaluacion = new CapaETL.Evaluacion();
                    evaluacion.nombre = txtNombre;
                    evaluacion.descripcion = txtDescripcion;
                    evaluacion.cantidadCalificaciones = Convert.ToInt32(txtCantidad);

                    respuesta = bllEvaluaciones.InsertarEvaluaciones(evaluacion);
                    if (respuesta.codigoRespuesta == clsConstantes.CodigosRespuestas.CODIGOCORRECTO)
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjEvaluacionAgregada, "/Evaluaciones/Evaluaciones");
                    }
                    else
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, respuesta.mensajeRespuesta, "/Evaluaciones/Evaluaciones");
                    }
                }
                return Content(CodigoJavaScript);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Evaluaciones/Evaluaciones");
                return Content(CodigoJavaScript);
            }
        }
        #endregion

        #region
        /// <summary>
        ///     Metodo que muestra una vista de calificaciones con un modelo de calificaciones
        /// </summary>
        /// <returns>Vista calificaciones</returns>
        public ActionResult Calificaciones()
        {
            try
            {
                return View(bllCalificaciones.MostrarCalificaciones().objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Evaluaciones/Calificaciones");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Metodo que retorna una vista donde se agregan las calificaciones
        /// </summary>
        /// <returns>Vista agregar calificaciones</returns>
        public ActionResult AgregarCalificaciones()
        {
            try
            {
                return View(bllEvaluaciones.MostrarEvaluaciones().objetoRespuesta);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Evaluaciones/Calificaciones");
                return Content(CodigoJavaScript);
            }
        }

        /// <summary>
        ///     Metodo que inserta las calificaciones
        /// </summary>
        /// <param name="optEvaluaciones"></param>
        /// <param name="txtCedula"></param>
        /// <param name="optCalificacion"></param>
        /// <returns>Codigo js que tiene un mensaje de respuesta</returns>
        public ActionResult InsertarCalificaciones(string optEvaluaciones, string txtCedula, string optCalificacion)
        {
            try
            {
                string CodigoJavaScript;
                if (string.IsNullOrEmpty(txtCedula))
                {
                    //Se le da formato a la funcion javascript de retorno
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjErrorCamposVacios, "/Evaluaciones/AgregarCalificaciones");
                }
                else if (optEvaluaciones == "0")
                {
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjEvaluacionNoSeleccionada, "/Evaluaciones/AgregarCalificaciones");
                }
                else if (optCalificacion == "0")
                {
                    CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjCalificacionNoSeleccionada, "/Evaluaciones/AgregarCalificaciones");
                }
                else
                {
                    CapaETL.Calificacion calificacion = new CapaETL.Calificacion();
                    calificacion.codigoEvaluacion = Convert.ToInt32(optEvaluaciones);
                    calificacion.cedulaCalificante = txtCedula;
                    calificacion.calificacion = Convert.ToInt32(optCalificacion);

                    respuesta = bllCalificaciones.InsertarCalificaciones(calificacion);
                    if (respuesta.codigoRespuesta == clsConstantes.CodigosRespuestas.CODIGOCORRECTO)
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, Mensajes.msjCalificacionAgregada, "/Evaluaciones/Calificaciones");
                    }
                    else
                    {
                        //Se le da formato a la funcion javascript de retorno
                        CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, respuesta.mensajeRespuesta, "/Evaluaciones/Calificaciones");
                    }
                }
                return Content(CodigoJavaScript);
            }
            catch (Exception ex)
            {
                string CodigoJavaScript = string.Format(clsConstantes.SCRIPT_MENSAJE, ex.Message, "/Evaluaciones/Calificaciones");
                return Content(CodigoJavaScript);
            }
        }
        #endregion
    }
}

BCR.PracticaMinions4.UIL/Views/Evaluaciones/AgregarCalificaciones.cshtml
@model List<BCR.PracticaMinions4.ETL.Evaluacion>

@{
    ViewBag.Title = "AgregarCalificaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Calificaciones</h2>

<table style="width: 50%">

    @* Formulario que manda parametros de insertar al controlador *@
    @using (Html.BeginForm("InsertarCalificaciones", "Evaluaciones", FormMethod.Post))
    {
        <tr>
            <td align="left" style="width: 50%">
                <h6>Evaluación:</h6>
            </td>
            <td style="width: 40%">
                <select id="optEvaluaciones" name="optEvaluaciones" class="form-control">
                    <option value="0">Seleccione una evaluación</option>
                    @{
                        foreach (var evaluacion in Model)
                        {
                            <option value="@evaluacion.codigoEvaluacion">@evaluacion.codigoEvaluacion - @evaluacion.nombre</option>
                        }
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 50%">
                <h6>Cédula:</h6>
            </td>
            <td style="width: 40%">
                <input type="text" name="txtCedula" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 50%">
                <h6>Calificación:</h6>
            </td>
            <td style="width: 40%">
                <select id="optCalificacion" name="optCalificacion" class="form-control">
                    <option value="0">Seleccione una calificación</option>
                    @{
                        for (var i = 1; i < 11; i++)
                        {
                            <option value="@i">@i</option>
                        }
                    }
                </select>
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Insertar Calificación</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Evaluaciones/AgregarEvaluaciones.cshtml
@{
    ViewBag.Title = "AgregarEvaluaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Agregar Evaluaciones</h2>

<table style="width: 50%">

    @* Formulario que manda parametros de insertar al controlador *@
    @using (Html.BeginForm("InsertarEvaluaciones", "Evaluaciones", FormMethod.Post))
    {
        <tr>
            <td align="left">
                Nombre de la evaluación:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtNombre" class="form-control" />
            </td>
        </tr>
        <tr>
            <td align="left">
                Descripción:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtDescripcion" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left">
                Cantidad de calificaciones:
            </td>
            <td style="width: 50%">
                <input type="text" name="txtCantidad" class="form-control">
            </td>
        </tr>
        <tr>
            <td align="left" style="width: 40%">
                <button type="submit" class="btn btn-success">Insertar Evaluación</button>
            </td>
        </tr>
    }
</table>

BCR.PracticaMinions4.UIL/Views/Evaluaciones/Calificaciones.cshtml
@model List<BCR.PracticaMinions4.ETL.Calificacion>

@{
    ViewBag.Title = "Calificaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Calificaciones</h2>

@* Boton donde se agrega las calificaciones *@
<table style="width: 100%">
    <tr>
        <td style="width: 80%">
        </td>
        <td style="width: 16%" align="right">
            <button type="button" class="btn btn-success" onclick="location.href='/Evaluaciones/AgregarCalificaciones'">Agregar Calificación</button>
        </td>
    </tr>
</table>

@* Tabla donde se muestra la lista de calificaciones *@
<table class="table table-bordered">
    <thead class="bg-info">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre de la evaluación</th>
            <th scope="col">Descripción de la evaluación</th>
            <th scope="col">Cédula del calificante</th>
            <th scope="col">Calificación</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var calificacion in Model)
            {
                <tr>
                    <th scope="col">@calificacion.codigoCalificacion</th>
                    <th scope="col">@calificacion.nombreEvaluacion</th>
                    <th scope="col">@calificacion.descripcionEvaluacion</th>
                    <th scope="col">@calificacion.cedulaCalificante</th>
                    <th scope="col">@calificacion.calificacion</th>
                </tr>
            }
        }
    </tbody>
</table>

BCR.PracticaMinions4.UIL/Views/Evaluaciones/Evaluaciones.cshtml
@model List<BCR.PracticaMinions4.ETL.Evaluacion>

@{
    ViewBag.Title = "Evaluaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Evaluaciones</h2>
@* Boton donde agrega las evaluaciones *@
<table style="width: 100%">
    <tr>
        <td style="width: 80%">
        </td>
        <td style="width: 14%">
            <button type="button" class="btn btn-success" onclick="location.href='/Evaluaciones/AgregarEvaluaciones'">Agregar Evaluación</button>
        </td>
    </tr>
</table>

@* Tabla en la se muestra la lista de evaluaiones *@
<table class="table table-bordered">
    <thead class="bg-info">
        <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">Cantidad de calificaciones</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var evaluacion in Model)
            {
                <tr>
                    <th scope="col">@evaluacion.codigoEvaluacion</th>
                    <th scope="col">@evaluacion.nombre</th>
                    <th scope="col">@evaluacion.descripcion</th>
                    <th scope="col">@evaluacion.cantidadCalificaciones</th>
                </tr>
            }
        }
    </tbody>
</table>

BCR.PracticaMinions4.UIL/Views/Evaluaciones/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inicio de Evaluaciones</h2>

<br />
@* Tabla de botones *@
<table>
    <tr>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Evaluaciones/Evaluaciones'">Evaluaciones</button>
        </td>
        <td>
            <button type="button" class="btn btn-info btn-lg" onclick="location.href='/Evaluaciones/Calificaciones'">Calificaciones</button>
        </td>
    </tr>
</table>